### ISSUE TITLE
Incorrect torrserver executable file name

### ISSUE THREAD

**Issue by macrokernel** [vladlenas/Terramaster-TorrServer#1]
Incorrect torrserver executable file name: /usr/local/torrserver/bin/toorserver - should be /usr/local/torrserver/bin/torrserver

**Comment by vladlenas** [comment]
this is just a dummy template, but thanks anyway
https://github.com/vladlenas/Terramaster-TorrServer/commit/1e1f5695356dd2ff3a76f209b453e80bafdcc78a
